# Generated by Django 5.0.6 on 2024-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_forgotpassword_alter_jobseeker_expertise_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
